import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  // Here we'll do a fetch to some backend.
  // Dummy data for now to illustrate the point :)
  const sports = ["Lorem", "Ipsum", "Dolor", "Catana", "Banana"];

  return (
    <div className={styles.container}>
      <Head>
        <title>Fem sporter på én dag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Velkommen til septembers <br /> <a href="/quintuplo">Quintuplo</a>!
        </h1>

        <p className={styles.description}>Månedens sporter er...</p>

        <div className={styles.grid}>
          {sports.map((sport) => {
            return (
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>{sport} &rarr;</h2>
                <p>Litt marketing om sporten.</p>
              </a>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by Smauet Technology Group
      </footer>
    </div>
  );
};

export default Home;
