import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { Sport } from "../types/sports";
import { CSSTransition, TransitionGroup } from "react-transition-group";

const Home: NextPage<{ sports: Sport[] }> = ({ sports }) => {
  const [isClicked, setIsClicked] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Fem sporter på én dag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Velkommen til septembers <br /> <a href="/quintuplo">Quintuplo</a>!
        </h1>

        <p className={styles.description}>Månedens sporter er...</p>

        <button
          className={styles.button}
          onClick={() => setIsClicked(!isClicked)}
        >
          Generer quintuplo
        </button>

        <div className={styles.grid}>
          {isClicked &&
            sports.map((sport) => {
              return (
                <a href="https://nextjs.org/docs" className={styles.card}>
                  <h2>{sport.title} &rarr;</h2>
                  <div className={styles.goalExplainerBox}>
                    <div className={styles.goalExplainerBoxElement}>
                      {sport.emoji}
                    </div>
                    <div className={styles.goalExplainerBoxElement}>Mål:</div>
                    <div className={styles.goalExplainerBoxElement}>
                      {sport.mål}
                    </div>
                  </div>

                  <p>{sport.marketing}</p>
                </a>
              );
            })}
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by Smauet Technology Group
      </footer>
    </div>
  );
};

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const sports = require("../data/sports.json");

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      sports,
    },
  };
}

export default Home;
