import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Sport } from "../types/sports";

const Home: NextPage<{ sports: Sport[] }> = ({ sports }) => {
  const [isClicked, setIsClicked] = useState(false);
  const [numberOfSports, setNumberOfSports] = useState(1);

  useEffect(() => {
    const timeout = setTimeout(() => {
      setNumberOfSports(numberOfSports + 1);
    }, 5000);

    return () => {
      clearTimeout(timeout);
    };
  }, [numberOfSports]);

  return (
    <div className="">
      <Head>
        <title>Fem sporter på én dag</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="">
          Velkommen til septembers <br /> <a href="/quintuplo">Quintuplo</a>!
        </h1>

        <p className={"">Månedens sporter er...</p>

        <button
          className=""
          onClick={() => {
            setIsClicked(!isClicked);
            setNumberOfSports(1);
          }}
        >
          Generer quintuplo
        </button>

        <div className="">
          {isClicked &&
            sports.slice(0, numberOfSports).map((sport) => {
              return (
                <a
                  href={`https://google.com/search?q=${sport.title}`}
                  className={styles.card}
                  key={sport.id}
                >
                  <h2>{sport.title} &rarr;</h2>
                  <div className="">
                    <div className="">
                      {sport.emoji}
                    </div>
                    <div className="">Mål:</div>
                    <div className="">
                      {sport.mål}
                    </div>
                  </div>

                  <p>{sport.marketing}</p>
                </a>
              );
            })}
        </div>
      </main>

      <footer className="">
        Powered by Smauet Technology Group
      </footer>
    </div>
  );
};

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const sports = require("../data/sports.json");

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      sports,
    },
  };
}

export default Home;
